ref/app1/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "app1"

urlpatterns = [
    path("", views.IndexView.as_view(), name='index'),
    path("services/", views.ServicesView.as_view(), name='services'),
    path("bemutatkozas/", views.Bemutakozas.as_view(), name="bemutatkozas"),
    path("referencia/", views.ReferenceView.as_view(), name="reference"),
    path("contact/", views.ContactView.as_view(), name="kapcsolat"),
    path("thanks/", views.Thanks.as_view(), name='thanks'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ref/ref/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app1.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ref/app1/models.py
from django.db import models

# Create your models here.

class Service(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=1000)
    price = models.IntegerField()

    def __str__(self):
        return self.name

class Customer(models.Model):
    email = models.EmailField()
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    message = models.TextField(max_length=2000)

    def __str__(self):
        return self.first_name + " " + self.last_name
    

class Reference(models.Model):
    name = models.CharField(max_length=40)
    image = models.ImageField(upload_to="reference/", null=True, blank=True)

    def __str__(self):
        return self.name

ref/app1/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView
from django.views import View
from .models import Service, Reference, Customer

# Create your views here.

class IndexView(TemplateView):
    
    template_name = "app1/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["ref"] = Reference.objects.get(pk=1)
        return context
    
class Bemutakozas(TemplateView):
    template_name = "app1/bemutatkozas.html"


class ServicesView(ListView):
    template_name = "app1/services.html"
    queryset = Service.objects.all()


class ReferenceView(ListView):
    template_name = "app1/reference.html"
    queryset = Reference.objects.all()


class Thanks(TemplateView):
    template_name = "app1/thanks.html"

class ContactView(View):

    def get(self, request):
        return render(request, "app1/contact.html")
    
    def post(self, request):
        fname = request.POST["fname"]
        lname = request.POST["lname"]
        email = request.POST["email"]
        message = request.POST["message"]
        new_customer = Customer(first_name=fname,last_name=lname,email=email,message=message)
        new_customer.save()
        return redirect("app1:thanks")

ref/app1/templates/app1/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--FAVICON-->
    <link rel="icon" type="image/x-icon" href="{% static 'app1/images/favicon.ico' %}">
    <title>Marton Geza - Gardener Extraordinaire</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <!-- Font Awesome CSS (for icons) -->
    <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>

    <!-- AOS CSS (for animations) -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'app1/css/styles.css' %}">

</head>
<body>

    <header>
        <div class="logo-frame">
            <a href="/">
                <img class='img-fluid' src="{% static 'app1/images/Marczi_logo.png' %}" alt="Marczi logo" width='50%' style="border:0;">
            </a>
            <h1>Marton Geza - Kertrendezés szakértő</h1>
            <p>Kertész szolgáltatások precízen és szenvedéllyel</p>
        </div>
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-dark">
                <a href="navbar-brand">Home</a>
                <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav m-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'app1:bemutatkozas' %}" data-aos="fade-down" data-aos-duration="1000">Bemutatkozás</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'app1:reference' %}" data-aos="fade-down" data-aos-duration="1000" data-aos-delay="200">Referenciák</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'app1:services' %}" data-aos="fade-down" data-aos-duration="1000" data-aos-delay="400">Szolgáltatások</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url "app1:kapcsolat" %}" data-aos="fade-down" data-aos-duration="1000" data-aos-delay="600">Kapcsolatfelvétel</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#" data-aos="fade-down" data-aos-duration="1000" data-aos-delay="800">Galéria</a>
                        </li>
                        <!-- Add more navbar items as needed -->
                    </ul>
                </div>
            </nav>
        </div>
    </header>
    
    {% block content %}{% endblock content %}
    <footer>
        <p>Keressen bátran az alábbi elérhetőségek egyikén:</p>
        <p><i class="fa-regular fa-envelope"></i> martongeza77@gmail.com | <span class="phone-num"><i class="fa-solid fa-mobile"></i> +36 30 314 0332</p></span>
    </footer>

    <!-- Bootstrap JS, jQuery, AOS JS -->
    <script	src="https://code.jquery.com/jquery-3.7.1.js"
			  integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4="
			  crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>

    <!-- Initialize AOS -->
    <script>
        AOS.init();
    </script>

</body>
</html>

ref/app1/templates/app1/bemutatkozas.html
{% extends "app1/base.html" %}
{% load static %}
{% block content %}
    
    <section class='container'>
        <p class="bemutatkozas-szoveg">Márton Géza vagyok, és a szívem a dísznövények és kertek iránt dobog. Kertészeti szakképesítésemet 1995-ben szereztem a Magyar Gyula Kertészeti Szakközépiskolában. Több mint 25 éve állítom szolgáltatásaimat ügyfeleim rendelkezésére, szakmai tapasztalattal, precíz munkavégzéssel és profi eszközökkel a kezemben.</p>
        <p class="bemutatkozas-szoveg">Specializációim közé tartozik a kertgondozás és növénykarbantartás, ahol nem csak a növényeket, de a kert egészét gondozom, hogy a természet harmóniáját tükrözze. Emellett széles körű tavaszi kertindító karbantartást nyújtok, és rendszeres kertgondozási csomagokkal állunk az ügyfelek rendelkezésére, hogy kertjük mindig a legjobb formájában ragyogjon.</p>
        <p class="bemutatkozas-szoveg">A kert nem csupán növények gyűjteménye, hanem egy személyes oázis, és célom, hogy minden ügyfelem kertje egyedi, az ő egyéni stílusukat tükröző területté váljon. Kreatív kertépítési munkákban és felújításokban is szakértő vagyok, és minden projektet lelkesedéssel kezelek, mintha saját kertem lenne.</p>
        <p class="bemutatkozas-szoveg">Ha Ön is szeretné kertjét egy tapasztalt és elkötelezett kertészre bízni, várom a kapcsolatfelvételt. Bízom benne, hogy együtt alakíthatjuk át kertjét egy élő, virágzó paradicsommá!</p>
    </section>
    <section class="text-center container">
        <img class='img-fluid' src="{% static 'app1/images/geza.jpg' %}" alt="Profilkep" width="40%">
    </section>

{% endblock content %}

ref/app1/templates/app1/contact.html
{% extends "app1/base.html" %}
{% load static %}

{% block content %}
<section class="container" style="padding:10px;">
        <div class="row justify-content-center">
            <div class="col-md-6">

                <h2 class="text-center mb-4">Írj egy üzenetet!</h2>

                <!-- Contact Form -->
                <form class="p-3" method="post">
                    {% csrf_token %}
                    <!-- Name Input -->
                    <div class="form-group">
                        <label for="fname">Vezetéknév:</label>
                        <input type="text" class="form-control" id="fname" name="fname" required>
                    </div>

                    <div class="form-group">
                        <label for="lname">Keresztnév:</label>
                        <input type="text" class="form-control" id="lname" name="lname" required>
                    </div>

                    <!-- Email Input -->
                    <div class="form-group">
                        <label for="email">Email:</label>
                        <input type="email" class="form-control" id="email" name="email" required>
                    </div>

                    <!-- Message Textarea -->
                    <div class="form-group">
                        <label for="message">Fejtsd ki kérlek miben tudok segíteni:</label>
                        <textarea class="form-control" id="message" name="message" rows="4" required></textarea>
                    </div>

                    <!-- Submit Button -->
                    <button type="submit" class="gardening-btn btn btn-block">Submit</button>

                </form>
                <!-- End Contact Form -->

            </div>
        </div>
</section>

{% endblock content %}

ref/app1/templates/app1/index.html
{% extends "app1/base.html" %}

{% load static %}
{% block content %}
<section>
    <!-- Your content goes here -->
    <h2>About Me</h2>
    <p>I am Marton Geza, a trustworthy and conscientious gardener with over 25 years of experience...</p>
</section>

<section>
    <!-- Your content goes here -->
    <h2>Services</h2>
    <p>My expertise lies in gardening, maintenance, lawn mowing, and garden building...</p>
    {% comment %} {% if ref.image %}
        <img class="img-fluid" src="{{ ref.image.url }}" alt="{{ref.image.name}}" width="500px" height="200px">
    {% endif %} {% endcomment %}
</section>
{% endblock content %}

ref/app1/templates/app1/reference.html
{% extends "app1/base.html" %}

{% block content %}
<div>
    <div class='mt-5 services-container'>
        {% for ref in object_list  %}
            <a href="#" >
                <div class="service-card">
                    <h2>{{ref.name}}</h2>                
                    <img src="{{ ref.image.url }}" style="width:80%;">
                </div>
            </a>
        {% endfor object_list %}

    </div>
</div>
{% endblock content %}

ref/app1/templates/app1/services.html
{% extends "app1/base.html" %}

{% block content %}
<div>
    <div class='mt-5 services-container'>
        {% for service in object_list  %}
        <div class="service-card">
            <h2>{{service.name}}</h2>
            <p>{{service.description}}</p>
            <h3>{{service.price}} HUF</h3>
        </div>

        {% endfor object_list %}
    </div>
</div>
{% endblock content %}

ref/app1/templates/app1/thanks.html
{% extends "app1/base.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6 text-center">

            <h2 class="mb-4">Köszönöm</h2>
            <p>Amint tudok válaszolok!</p>

            <!-- Link back to the contact form or another page -->
            <p class="mt-4"><a href="/">Főmenü</a></p>

        </div>
    </div>
</div>
{% endblock content %}